services:
  backend_app:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - ./secrets/mongo.env
  model_frontend_app:
    build: ./frontend
    ports:
      - '8501:8501'
    env_file:
      - ./secrets/backend.env
    depends_on:
      - backend_app